services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_ABBR}${COMPOSE_PROJECT_IMGK}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:4000
    volumes:
      - type: bind
        source: ${COMPOSE_PROJECT_PATH}
        target: /var/www/htdocs
    tty: true
    restart: unless-stopped
